name: Linter

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # make depends on poetry
      - name: Install dependencies
        run:
          pip install poetry
      - name: Run linter and pytest
        run: 
          make lint
